### ISSUE TITLE
Delete set not working?

### ISSUE THREAD

**Issue by Wyr3d** [WoW-MogIt/MogIt_SetTransmog#2]
IIRC, it was shift+left click to delete an unwanted saved set. This does not appear to be working at this time. Correct me if  I am wrong and it is some other button combination. Thanks

**Comment by Lombra** [comment]
I would have to check, but I don't remember there being such a key binding. Using the right click menu should be the way to go.

**Comment by Lombra** [comment]
I assume after seeing your comment on the other issue that you are referring to SetTransmog, which does not have the ability to delete sets directly from the menu.

**Comment by Wyr3d** [comment]
Nope, I meant the Mogit specific sets, but what I was trying to do was delete a duplicate copy from another character via the preview. Pretty sure you used to be able to do this by selecting load, find the offending set, and right clicking, or shift right clicking during the dropdown, but it no longer works.

However, it can still be deleted by switching to the character, navigating to their wishlist, and right-click deleting the set from there

**Comment by Lombra** [comment]
I don't believe there has been any such key binding. Certainly not one that's changed in the last few years. What we do have is shift-clicking in the set transmog menu to edit default wardrobe sets and, I believe, shift clicking item slots in the MogIt preview frame to remove them.

**Comment by Wyr3d** [comment]
Yeah, I was prolly confusing the two
